### ISSUE TITLE
Accepting Issues or Pull Requests?

### ISSUE THREAD

**Issue by nathan-hook** [NCAR/ssosample#1]
There are a couple of 'small' issues with the current release, would you be willing to either accept issues or even better pull requests for the fixes?

Thank you for your time and thank you for putting together this great example!

**Comment by UCARFA** [comment]
That would be great.  I created a dev branch and protected the merge on
master.  You can commit to dev and submit the pull request, and I can
merge.  I'll just need the github login for anyone that wants to be a
collaborator.

Steve

**Comment by sjwaltman** [comment]
I just added you as a collaborator.
